CREATE OR REPLACE FUNCTION SOMA( INTEGER, INTEGER ) RETURNS INTEGER LANGUAGE PLPGSQL AS $$
DECLARE

V1 ALIAS FOR $1;
V2 ALIAS FOR $2;
RES INTEGER := 0;
BEGIN
RES := V1 + V2;
IF RES > 10 THEN RES:= 50;
END IF;
RETURN RES;

END;
$$;


CREATE OR REPLACE FUNCTION TESTE1_PROC_AUDIT()
    RETURNS TRIGGER AS $TESTE1_AUDIT$
BEGIN
    INSERT INTO TESTE1_LOG VALUES(
        NEW.T1_ID,
        NEW.T1_NOME,
        NEW.T1_SALDO,
        USER,
        NOW(),
        TG_OP
    );
    RETURN NEW;
END;
$TESTE1_AUDIT$ LANGUAGE PLPGSQL;

