ALTER TABLE public.Quadras ADD CONSTRAINT Quadra_Endereço FOREIGN KEY (endereco_id)
REFERENCES public.Endereco (id) MATCH FULL
ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE public.Quadras ADD CONSTRAINT Quadra_Club FOREIGN KEY (club_id)
REFERENCES public.Club (id) MATCH FULL
ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE public.Quadras ADD CONSTRAINT Quadra_Tipo FOREIGN KEY (tipo_id)
REFERENCES public.TipoQuadra (id) MATCH FULL
ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE public.Alunos ADD CONSTRAINT Aluno_Cliente FOREIGN KEY (cliente_id)
REFERENCES public.Cliente (id) MATCH FULL
ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE public.Aulas ADD CONSTRAINT Aulas_Professor FOREIGN KEY (professor_id)
REFERENCES public.Professor (id) MATCH FULL
ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE public.Alunos ADD CONSTRAINT Aluno_Endereco FOREIGN KEY (endereco_id)
REFERENCES public.Endereco (id) MATCH FULL
ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE public.AlunoAula ADD CONSTRAINT Aluno_Aula FOREIGN KEY (aluno_id)
REFERENCES public.Alunos (id) MATCH FULL
ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE public.AlunoAula ADD CONSTRAINT Aula_Aluno FOREIGN KEY (aula_id)
REFERENCES public.Aulas (id) MATCH FULL
ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE public.HorariosQuadras ADD CONSTRAINT Quadra_Horario FOREIGN KEY (quadra_id)
REFERENCES public.Quadras (id) MATCH FULL
ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE public.HorariosQuadras ADD CONSTRAINT Horario_Aula FOREIGN KEY (quadra_id)
REFERENCES public.Aulas (id) MATCH FULL
ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE public.HorariosQuadras ADD CONSTRAINT Horario_Quadra FOREIGN KEY (Horario_id)
REFERENCES public.Horarios (id) MATCH FULL
ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE public.Professor ADD CONSTRAINT Professor_Endereco FOREIGN KEY (endereco_id)
REFERENCES public.Endereco (id) MATCH FULL
ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE public.Cliente ADD CONSTRAINT Cliente_Endereco FOREIGN KEY (endereco_id)
REFERENCES public.Endereco (id) MATCH FULL
ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE public.Adm ADD CONSTRAINT Adm_Endereco FOREIGN KEY (endereco_id)
REFERENCES public.Endereco (id) MATCH FULL
ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE public.Pagamento ADD CONSTRAINT Pagamento_Quadra FOREIGN KEY (quadra_id)
REFERENCES public.Quadras (id) MATCH FULL
ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE public.Pagamento ADD CONSTRAINT Pagamento_Cliente FOREIGN KEY (cliente_id)
REFERENCES public.Cliente (id) MATCH FULL
ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE public.Pagamento ADD CONSTRAINT Pagamento_Financeiro FOREIGN KEY(financeiro_id)
REFERENCES public.Financeiro(id) MATCH FULL
ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE public.Pagamento ADD CONSTRAINT Pagamento_Aluguel FOREIGN KEY(aluguel_id)
REFERENCES public.Aluguel(id) MATCH FULL
ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE public.Club ADD CONSTRAINT Club_Endereco FOREIGN KEY (cedeEndereco_id)
REFERENCES public.Endereco (id) MATCH FULL
ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;