INSERT INTO TB_Curso VALUES (1,'Biomedicina','Matemática',1,1,'B');
INSERT INTO TB_Curso VALUES (2,'Biomedicina','Física',1,1,'B');
INSERT INTO TB_Curso VALUES (3,'Biomedicina','Estatística',1,1,'B');
INSERT INTO TB_Curso VALUES (4,'Biomedicina','Computação',1,1,'B');
INSERT INTO TB_Curso VALUES (5,'Agronomia','Química',1,1,'B');
INSERT INTO TB_Curso VALUES (6,'Agronomia','Física',1,1,'B');
INSERT INTO TB_Curso VALUES (7,'Agronomia','Matemática',1,1,'B');
INSERT INTO TB_Curso VALUES (8,'Agronomia','Química',1,1,'B');
INSERT INTO TB_Curso VALUES (9,'Agronomia','Química',1,1,'B');
INSERT INTO TB_Curso VALUES (10,'Agronomia','Eng. Civil',1,1,'B');
INSERT INTO TB_Curso VALUES (11,'Agronomia','Matemática',1,1,'B');
INSERT INTO TB_Curso VALUES (12,'Agronomia','Estatística',1,1,'B');
INSERT INTO TB_Curso VALUES (13,'Agronomia','Estatística',1,1,'B');
INSERT INTO TB_Curso VALUES (14,'Ciências Contábeis','Matemática',1,1,'B');
INSERT INTO TB_Curso VALUES (15,'Ciências Contábeis','Computação',1,1,'B');
INSERT INTO TB_Curso VALUES (16,'Ciências Contábeis','Matemática',1,1,'B');
INSERT INTO TB_Curso VALUES (17,'Ciências Contábeis','Estatística',1,1,'B');
INSERT INTO TB_Curso VALUES (18,'Ciências Contábeis','Estatística',1,1,'B');
INSERT INTO TB_Curso VALUES (19,'Economia','Estatística',1,1,'B');
INSERT INTO TB_Curso VALUES (20,'Economia','Matemática',1,1,'B');
INSERT INTO TB_Curso VALUES (21,'Economia','Estatística',1,1,'B');
INSERT INTO TB_Curso VALUES (22,'Economia','Matemática',1,1,'B');
INSERT INTO TB_Curso VALUES (23,'Economia','Matemática',1,1,'B');
INSERT INTO TB_Curso VALUES (24,'Geografia','Estatística',1,1,'L');
INSERT INTO TB_Curso VALUES (25,'Geografia','Química',1,1,'B');
INSERT INTO TB_Curso VALUES (26,'Geografia','Estatística',1,1,'B e L');
INSERT INTO TB_Curso VALUES (27,'Ciências Sociais','Estatística',1,1,'L');
INSERT INTO TB_Curso VALUES (28,'Ciências Sociais','Estatística',1,1,'L');
INSERT INTO TB_Curso VALUES (29,'LEA','Estatística',1,1,'B');
INSERT INTO TB_Curso VALUES (30,'Ciências Biológicas','Matemática',1,1,'B+L');
INSERT INTO TB_Curso VALUES (31,'Ciências Biológicas','Física',1,1,'B+L');
INSERT INTO TB_Curso VALUES (32,'Ciências Biológicas','Química',1,1,'B+L');
INSERT INTO TB_Curso VALUES (33,'Ciências Biológicas','Estatística',1,1,'B+L');
INSERT INTO TB_Curso VALUES (34,'Ciências Biológicas','Matemática',1,1,'B+L');
INSERT INTO TB_Curso VALUES (35,'Ciências Biológicas','Física',1,1,'B+L');
INSERT INTO TB_Curso VALUES (36,'Ciências Biológicas','Química',1,1,'B+L');
INSERT INTO TB_Curso VALUES (37,'Ciências Biológicas','Estatística',1,1,'B+L');
INSERT INTO TB_Curso VALUES (38,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (39,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (40,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (41,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (42,'Eng. Mecânica','Eng. Química',1,1,'B');
INSERT INTO TB_Curso VALUES (43,'Eng. Mecânica','Eng. Química',1,1,'B');
INSERT INTO TB_Curso VALUES (44,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (45,'Eng. Mecânica','Eng. Química',1,1,'B');
INSERT INTO TB_Curso VALUES (46,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (47,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (48,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (49,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (50,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (51,'Eng. Mecânica','Eng. Química',1,1,'B');
INSERT INTO TB_Curso VALUES (52,'Eng. Mecânica','Eng. Química',1,1,'B');
INSERT INTO TB_Curso VALUES (53,'Eng. Mecânica','Eng. Química',1,1,'B');
INSERT INTO TB_Curso VALUES (54,'Eng. Mecânica','Eng. Química',1,1,'B');
INSERT INTO TB_Curso VALUES (55,'Eng. Mecânica','Eng. Química',1,1,'B');
INSERT INTO TB_Curso VALUES (56,'Eng. Mecânica','Eng. Produção',1,1,'B');
INSERT INTO TB_Curso VALUES (57,'Eng. Mecânica','Eng. Produção',1,1,'B');
INSERT INTO TB_Curso VALUES (58,'Eng. Mecânica','Matemática',1,1,'B');
INSERT INTO TB_Curso VALUES (59,'Eng. Mecânica','Matemática',1,1,'B');
INSERT INTO TB_Curso VALUES (60,'Eng. Mecânica','Física',1,1,'B');
INSERT INTO TB_Curso VALUES (61,'Eng. Mecânica','Matemática',1,1,'B');
INSERT INTO TB_Curso VALUES (62,'Eng. Mecânica','Física',1,1,'B');
INSERT INTO TB_Curso VALUES (63,'Eng. Mecânica','Matemática',1,1,'B');
INSERT INTO TB_Curso VALUES (64,'Eng. Mecânica','Física',1,1,'B');
INSERT INTO TB_Curso VALUES (65,'Eng. Mecânica','Física',1,1,'B');
INSERT INTO TB_Curso VALUES (66,'Eng. Mecânica','Física',1,1,'B');
INSERT INTO TB_Curso VALUES (67,'Eng. Mecânica','Física',1,1,'B');
INSERT INTO TB_Curso VALUES (68,'Eng. Mecânica','Matemática',1,1,'B');
INSERT INTO TB_Curso VALUES (69,'Eng. Mecânica','Matemática',1,1,'B');
INSERT INTO TB_Curso VALUES (70,'Eng. Mecânica','Física',1,1,'B');
INSERT INTO TB_Curso VALUES (71,'Eng. Mecânica','Química',1,1,'B');
INSERT INTO TB_Curso VALUES (72,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (73,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (74,'Eng. Mecânica','Matemática',1,1,'B');
INSERT INTO TB_Curso VALUES (75,'Eng. Mecânica','Eng. Química',1,1,'B');
INSERT INTO TB_Curso VALUES (76,'Eng. Mecânica','Física',1,1,'B');
INSERT INTO TB_Curso VALUES (77,'Eng. Mecânica','Química',1,1,'B');
INSERT INTO TB_Curso VALUES (78,'Eng. Mecânica','Computação',1,1,'B');
INSERT INTO TB_Curso VALUES (79,'Eng. Mecânica','Física',1,1,'B');
INSERT INTO TB_Curso VALUES (80,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (81,'Eng. Mecânica','Computação',1,1,'B');
INSERT INTO TB_Curso VALUES (82,'Eng. Mecânica','Eng. Elétrica',1,1,'B');
INSERT INTO TB_Curso VALUES (83,'Eng. Mecânica','Eng. Produção',1,1,'B');
INSERT INTO TB_Curso VALUES (84,'Eng. Mecânica','Eng. Elétrica',1,1,'B');
INSERT INTO TB_Curso VALUES (85,'Eng. Mecânica','Eng. Produção',1,1,'B');
INSERT INTO TB_Curso VALUES (86,'Eng. Mecânica','Eng. Elétrica',1,1,'B');
INSERT INTO TB_Curso VALUES (87,'Eng. Mecânica','Eng. Química',1,1,'B');
INSERT INTO TB_Curso VALUES (88,'Eng. Mecânica','Eng. Química',1,1,'B');
INSERT INTO TB_Curso VALUES (89,'Eng. Mecânica','Eng. Química',1,1,'B');
INSERT INTO TB_Curso VALUES (90,'Eng. Mecânica','Eng. Produção',1,1,'B');
INSERT INTO TB_Curso VALUES (91,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (92,'Eng. Mecânica','Física',1,1,'B');
INSERT INTO TB_Curso VALUES (93,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (94,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (95,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (96,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (97,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (98,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (99,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (100,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (101,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (102,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (103,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (104,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (105,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (106,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (107,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (108,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (109,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (110,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (111,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (112,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (113,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (114,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (115,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (116,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (117,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (118,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (119,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (120,'Eng. Mecânica','Eng. Produção',1,1,'B');
INSERT INTO TB_Curso VALUES (121,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (122,'Eng. Mecânica','Eng. Mecânica',1,1,'B');
INSERT INTO TB_Curso VALUES (123,'Eng. Civil','Química',1,1,'B');
INSERT INTO TB_Curso VALUES (124,'Eng. Civil','Matemática',1,1,'B');
INSERT INTO TB_Curso VALUES (125,'Eng. Civil','Física',1,1,'B');
INSERT INTO TB_Curso VALUES (126,'Eng. Civil','Matemática',1,1,'B');
INSERT INTO TB_Curso VALUES (127,'Eng. Civil','Física',1,1,'B');
INSERT INTO TB_Curso VALUES (128,'Eng. Civil','Eng. Civil',1,1,'B');
INSERT INTO TB_Curso VALUES (129,'Eng. Civil','Eng. Civil',1,1,'B');
INSERT INTO TB_Curso VALUES (130,'Eng. Civil','Eng. Civil',1,1,'B');
INSERT INTO TB_Curso VALUES (131,'Eng. Civil','Química',1,1,'B');
INSERT INTO TB_Curso VALUES (132,'Eng. Civil','Química',1,1,'B');
INSERT INTO TB_Curso VALUES (133,'Eng. Civil','Matemática',1,1,'B');
INSERT INTO TB_Curso VALUES (134,'Eng. Civil','Física',1,1,'B');
INSERT INTO TB_Curso VALUES (135,'Eng. Civil','Matemática',1,1,'B');
INSERT INTO TB_Curso VALUES (136,'Eng. Civil','Física',1,1,'B');
INSERT INTO TB_Curso VALUES (137,'Eng. Civil','Computação',1,1,'B');
INSERT INTO TB_Curso VALUES (138,'Eng. Civil','Eng. Civil',1,1,'B');
INSERT INTO TB_Curso VALUES (139,'Eng. Civil','Matemática',1,1,'B');
INSERT INTO TB_Curso VALUES (140,'Eng. Civil','Estatística',1,1,'B');
INSERT INTO TB_Curso VALUES (141,'Eng. Civil','Física',1,1,'B');
INSERT INTO TB_Curso VALUES (142,'Eng. Civil','Eng. Civil',1,1,'B');
INSERT INTO TB_Curso VALUES (143,'Eng. Civil','Computação',1,1,'B');
INSERT INTO TB_Curso VALUES (144,'Eng. Civil','Eng. Civil',1,1,'B');
INSERT INTO TB_Curso VALUES (145,'Eng. Civil','Eng. Civil',1,1,'B');
INSERT INTO TB_Curso VALUES (146,'Eng. Civil','Matemática',1,1,'B');
INSERT INTO TB_Curso VALUES (147,'Eng. Civil','Matemática',1,1,'B');
INSERT INTO TB_Curso VALUES (148,'Eng. Civil','Eng. Civil',1,1,'B');
INSERT INTO TB_Curso VALUES (149,'Eng. Civil','Eng. Elétrica',1,1,'B');
INSERT INTO TB_Curso VALUES (150,'Eng. Civil','Eng. Civil',1,1,'B');
INSERT INTO TB_Curso VALUES (151,'Eng. Civil','Eng. Civil',1,1,'B');
INSERT INTO TB_Curso VALUES (152,'Eng. Civil','Eng. Civil',1,1,'B');
INSERT INTO TB_Curso VALUES (153,'Eng. Civil','Eng. Civil',1,1,'B');
INSERT INTO TB_Curso VALUES (154,'Eng. Civil','Eng. Civil',1,1,'B');
INSERT INTO TB_Curso VALUES (155,'Eng. Civil','Eng. Civil',1,1,'B');
INSERT INTO TB_Curso VALUES (156,'Eng. Civil','Matemática',1,1,'B');

INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,1,'B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,1,'B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,1,'B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Civil','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Estatística',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Mecânica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Mecânica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Mecânica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Mecânica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Mecânica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Mecânica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Produção','Eng. Produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Estatística',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Elétrica','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Estatística',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Civil',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Elétrica',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Eng. Química','Eng. produção',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Estatística',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','DCET',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','DCET',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','DCET',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','DCET',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','DCET',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Física','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','COMPUTAÇÃO',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Química',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','DCET',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','COMPUTAÇÃO',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Estatística',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','DCET',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','DCET',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','DCET',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','DCET',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Física','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','COMPUTAÇÃO',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','COMPUTAÇÃO',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Estatística',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Estatística',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Computação',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Estatística',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Matemática','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Química','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Química','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Química','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Química','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Química','Estatística',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Química','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Química','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Química','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Química','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Química','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Química','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Química','Matemática',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Química','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Química','Física',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Química','Química',1,'Computacao','L');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Física',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Estatística',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Computação','Computação',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Administração','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Administração','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Administração','Matemática',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Administração','Estatística',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Administração','Estatística',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Enfermagem','Estatística',1,'Computacao','B');
INSERT INTO TB_Curso VALUES ( ,'Medicina Veterinária','Estatística',1,'Computacao','B');
